name: Docs

on: [push, pull_request]

permissions:
  contents: read  # for dorny/paths-filter to fetch a list of changed files
  pull-requests: read  # for dorny/paths-filter to read pull requests

jobs:
  Salt:
    name: Build Salt Documentation
    runs-on: ${{ github.event.repository.private && fromJSON('["self-hosted", "linux", "medium", "x86_64"]') || 'ubuntu-latest' }}

    container:
      image: ghcr.io/saltstack/salt-ci-containers/python:3.8

    steps:

    - name: Install System Deps
      run: |
        apt-get update
        apt-get upgrade debian-keyring -y
        echo "deb http://deb.debian.org/debian bookworm-backports main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y enchant-2 git gcc imagemagick make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev xz-utils

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add Git Safe Directory
      run: |
        git config --global --add safe.directory $(pwd)

    - name: Install Nox
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: json
        filters: |
          docs:
            - doc/**

    - name: Install Python Requirements
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run:
        nox --install-only --forcecolor -e 'docs-html(compress=False, clean=True)'

    - name: Build Docs
      env:
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        nox --forcecolor -e 'docs-html(compress=False, clean=True)'

    - name: Store Generated Documentation
      uses: actions/upload-artifact@v2
      with:
        name: salt-html-docs
        path: doc/_build/html

  Manpages:
    name: Build Salt man Pages
    runs-on: ${{ github.event.repository.private && fromJSON('["self-hosted", "linux", "medium", "x86_64"]') || 'ubuntu-latest' }}

    container:
      image: ghcr.io/saltstack/salt-ci-containers/python:3.8

    steps:

    - name: Install System Deps
      run: |
        apt-get update
        apt-get upgrade debian-keyring -y
        echo "deb http://deb.debian.org/debian bookworm-backports main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y enchant-2 git gcc imagemagick make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev

    - uses: actions/checkout@v3

    - name: Add Git Safe Directory
      run: |
        git config --global --add safe.directory $(pwd)

    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: json
        filters: |
          docs:
            - doc/**

    - name: Install Nox
      if: github.event_name == 'push' || steps.changed-files.outputs.docs == 'true'
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Install Python Requirements
      if: github.event_name == 'push' || steps.changed-files.outputs.docs == 'true'
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run:
        nox --install-only --forcecolor -e 'docs-man(compress=False, update=False, clean=True)'

    - name: Build Manpages
      if: github.event_name == 'push' || steps.changed-files.outputs.docs == 'true'
      env:
        SKIP_REQUIREMENTS_INSTALL: YES
      run: |
        nox --forcecolor -e 'docs-man(compress=False, update=False, clean=True)'

    - name: Store Generated Documentation
      if: github.event_name == 'push' || steps.changed-files.outputs.docs == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: salt-man-pages
        path: doc/_build/man
